In [11]:
import pubchempy as pcp
import pandas as pd
import time
import gzip
from rdkit import Chem
from rdkit.Chem import inchi
from tqdm import tqdm

In [12]:
df = pd.read_csv("../data/nodes/SmallMolecule.csv")
def smiles_to_inchikey(smi: str):
    m = Chem.MolFromSmiles(smi)
    if m is None:
        return None
    return inchi.MolToInchiKey(m)

df["inchikey"] = df["content"].astype(str).str.strip().apply(smiles_to_inchikey)

[17:15:07] WARNING: not removing hydrogen atom without neighbors
[17:15:07] WARNING: not removing hydrogen atom without neighbors
[17:15:54] bond type above 3 (12) is treated as unspecified!
[17:15:54] bond type above 3 (12) is treated as unspecified!
[17:15:54] Invalid InChI prefix in generating InChI Key
[17:16:04] bond type above 3 (12) is treated as unspecified!
[17:16:04] bond type above 3 (12) is treated as unspecified!
[17:16:04] bond type above 3 (12) is treated as unspecified!
[17:16:04] Invalid InChI prefix in generating InChI Key
[17:17:33] bond type above 3 (17) is treated as unspecified!
[17:17:33] Invalid InChI prefix in generating InChI Key
[17:20:11] bond type above 3 (17) is treated as unspecified!
[17:20:11] bond type above 3 (17) is treated as unspecified!
[17:20:11] bond type above 3 (17) is treated as unspecified!
[17:20:11] Invalid InChI prefix in generating InChI Key
[17:20:11] bond type above 3 (17) is treated as unspecified!
[17:20:11] bond type above 3 (17) is treated as unspecified!
[17:20:11] bond type above 3 (17) is treated as unspecified!
[17:20:11] Invalid InChI prefix in generating InChI Key
[17:20:11] bond type above 3 (17) is treated as unspecified!
[17:20:11] bond type above 3 (17) is treated as unspecified!
[17:20:11] bond type above 3 (17) is treated as unspecified!
[17:20:11] Invalid InChI prefix in generating InChI Key
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] Invalid InChI prefix in generating InChI Key
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] Invalid InChI prefix in generating InChI Key
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] Invalid InChI prefix in generating InChI Key
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] Invalid InChI prefix in generating InChI Key
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] Invalid InChI prefix in generating InChI Key
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] bond type above 3 (17) is treated as unspecified!
[17:20:38] Invalid InChI prefix in generating InChI Key
[17:20:40] bond type above 3 (17) is treated as unspecified!
[17:20:40] bond type above 3 (17) is treated as unspecified!
[17:20:40] Invalid InChI prefix in generating InChI Key
[17:20:40] bond type above 3 (17) is treated as unspecified!
[17:20:40] bond type above 3 (17) is treated as unspecified!
[17:20:40] Invalid InChI prefix in generating InChI Key
[17:20:40] bond type above 3 (17) is treated as unspecified!
[17:20:40] bond type above 3 (17) is treated as unspecified!
[17:20:40] Invalid InChI prefix in generating InChI Key
[17:20:52] bond type above 3 (17) is treated as unspecified!
[17:20:52] bond type above 3 (17) is treated as unspecified!
[17:20:52] Invalid InChI prefix in generating InChI Key
[17:20:52] bond type above 3 (17) is treated as unspecified!
[17:20:52] bond type above 3 (17) is treated as unspecified!
[17:20:52] bond type above 3 (17) is treated as unspecified!
[17:20:52] Invalid InChI prefix in generating InChI Key
[17:21:33] bond type above 3 (17) is treated as unspecified!
[17:21:33] Invalid InChI prefix in generating InChI Key
[17:21:33] bond type above 3 (17) is treated as unspecified!
[17:21:33] Invalid InChI prefix in generating InChI Key
[17:21:38] bond type above 3 (17) is treated as unspecified!
[17:21:38] bond type above 3 (17) is treated as unspecified!
[17:21:38] Invalid InChI prefix in generating InChI Key
[17:21:47] bond type above 3 (17) is treated as unspecified!
[17:21:47] bond type above 3 (17) is treated as unspecified!
[17:21:47] Invalid InChI prefix in generating InChI Key
[17:21:47] bond type above 3 (17) is treated as unspecified!
[17:21:47] bond type above 3 (17) is treated as unspecified!
[17:21:47] Invalid InChI prefix in generating InChI Key

In [25]:
need = set(df["inchikey"].dropna().unique())

out = []  # (inchikey, cid)

with gzip.open("../data/pubchem/CID-InChI-Key.gz", "rt", encoding="utf-8", errors="ignore") as f:
    for line in f:
        parts = line.strip().split()

        cid = int(parts[0])
        inchikey = parts[-1]

        if inchikey in need:
            out.append((inchikey, cid))
            need.remove(inchikey)
            if not need:
                break

map_df = pd.DataFrame(out, columns=["inchikey", "cid"])
map_df

                            inchikey        cid
0        VYZAHLCBVHPDDF-UHFFFAOYSA-N          6
1        MUIPLRMGAXZWSQ-UHFFFAOYSA-N          7
2        HERSSAVMHCMYSQ-UHFFFAOYSA-N         16
3        GLDQAMYCGOIJDV-UHFFFAOYSA-N         19
4        HWXBTNAVRSUOJR-UHFFFAOYSA-N         43
...                              ...        ...
1242400  PJLOZUMADBELJZ-YAELJHOLSA-N  177668511
1242401  WYAXEPKCXNISBM-UHFFFAOYSA-N  177668512
1242402  SVNIJYDUCDBSDR-UHFFFAOYSA-N  177668513
1242403  BYMLLYZVHHLEBE-CQSZACIVSA-N  177668516
1242404  QQJWZNXLWRBBHE-KRLHIGCXSA-N  177668517

[1242405 rows x 2 columns]

In [26]:
pd.read_csv("../data/1425448.csv")

,PUBCHEM_RESULT_TAG,PUBCHEM_SID,PUBCHEM_CID,PUBCHEM_EXT_DATASOURCE_SMILES,PUBCHEM_ACTIVITY_OUTCOME,PUBCHEM_ACTIVITY_SCORE,PUBCHEM_ACTIVITY_URL,PUBCHEM_ASSAYDATA_COMMENT,Standard Type,Activity Comment
0,RESULT_TYPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STRING,STRING
1,RESULT_DESCR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standardized activity type (e.g. IC50 rather t...,Additional comments
2,1,160708737.0,16058702.0,C1CN(CCN1C2=NC=NC3=C2OC4=CC=CC=C43)C(=S)NCC5=C...,Unspecified,NaN,NaN,Potential missing data,Activity,Non-Toxic

In [29]:
len(need)

1301937